### ISSUE TITLE
No Red INK

### ISSUE THREAD

**Issue by ReallyItsGrammaticallyCorrect** [NoRedInk/rspec-retry#85]
# NO RED INK
  No Red Ink has issues that need to be addressed. For example, if it's not exactly one of the ways they 
have it, then that means your answer is wrong. However, I will have answers that are grammatically correct and they will still be marked wrong....... it is really irritating. I will look at other problems just like it and those are correct, but this one isn't even though it follows the same exact guidelines. To be honest, I believe it's their way of making sure you don't get 100% since nothing can ever be "perfect". It needs to be fixed. I'm tired of getting 90%'s or 95%'s on tests that I deserve an 100% for just because there's something wrong with their system.

**Comment by ento** [comment]
@ReallyItsGrammaticallyCorrect Our support team will be better able to answer this kind of concern you just wrote in. Please send any issues or feedbacks you have to support@noredink.com!

I'm going to close this issue, so that this issue tracker holds issues that relate directly to the rspec-retry library, but also looking forward to improving NoRedInk in response to your feedback to the support team.
